### ISSUE TITLE
!!here

### ISSUE THREAD

**Issue by Adogs1** [DancingSnow0517/MCDR-Command-Exporter#2]
在服务端没有注册佛冷的!!here命令，以至于无法在客户端上导出

**Comment by DancingSnow0517** [comment]
那么你装了here插件吗？

**Comment by DancingSnow0517** [comment]
麻烦将问题描述清楚一些

**Comment by Adogs1** [comment]
> 麻烦将问题描述清楚一些

我安装了here，意思就是在客户端上输入!!he，无法找到here的补全命令

**Comment by DancingSnow0517** [comment]
服务器有安装mod吗？有没有安装这个插件？

**Comment by Adogs1** [comment]
> 服务器有安装mod吗？有没有安装这个插件？

都有

**Comment by DancingSnow0517** [comment]
看看server的config里有没有生成node.json?

**Comment by DancingSnow0517** [comment]
不对，我好像知道为啥了，用的fallen那个here是吗？那个没有使用MCDR的命令树来注册命令，所以我这个插件没法导出这个命令，也就不会显示出来

**Comment by Adogs1** [comment]
> 不对，我好像知道为啥了，用的fallen那个here是吗？那个没有使用MCDR的命令树来注册命令，所以我这个插件没法导出这个命令，也就不会显示出来

对，我在服务端上找不到here那个命令，以为这个插件是跟随服务端注册命令的，现在看来没办法了
